ansible_managed: "Ansible managed!"

routers:
  - name: CR3
    bgp_peer_ipv4_address: "45.151.166.3"
    bgp_peer_ipv6_address: "2001:678:b7c::3"
  - name: CR4
    bgp_peer_ipv4_address: "45.151.166.4"
    bgp_peer_ipv6_address: "2001:678:b7c::4"

fastd_secret_seed: "{{ (config_context|first).fastd_secret_seed }}"

client_ipv4_container: "10.0.0.0/8"
client_bridge_interface: "{{ interfaces | selectattr('name', 'equalto', 'br-client') | first }}"
gateway_ipv4_address: >-
  {{ client_bridge_interface.ip_addresses |
      map(attribute='address') |
      ansible.utils.ipv4 |
      ansible.utils.ipaddr(client_ipv4_container) |
      first
  }}
gateway_ipv6_address: >-
  {{ client_bridge_interface.ip_addresses |
      map(attribute='address') |
      ansible.utils.ipv6 |
      ansible.utils.ipaddr('public') |
      first
  }}

client_ipv4_start_address_int: "{{ gateway_ipv4_address | ansible.utils.ipaddr('network') | ansible.utils.ipaddr('int') }}"
dhcp_range_start_address_int: "{{ (config_context|first).dhcp_range.start_address|ansible.utils.ipaddr('int') }}"
dhcp_range_end_address_int: "{{ (config_context|first).dhcp_range.end_address|ansible.utils.ipaddr('int') }}"
dhcp_pool_offset: "{{ (dhcp_range_start_address_int|int) - (client_ipv4_start_address_int|int) - 1 }}"
dhcp_pool_size: "{{ (dhcp_range_end_address_int|int) - (dhcp_range_start_address_int|int) }}"

# Private Anycast Address in the domain used for reaching DNS
anycast_ipv4_service_address: >-
  {{ loopback_interface.ip_addresses |
      selectattr('role.value', 'equalto', 'anycast') |
      map(attribute='address') |
      ansible.utils.ipv4 |
      first
  }}
anycast_ipv6_service_address: >-
  {{ loopback_interface.ip_addresses |
      selectattr('role.value', 'equalto', 'anycast') |
      map(attribute='address') |
      ansible.utils.ipv6 |
      first
  }}

wan_interface: "{{ interfaces | selectattr('name', 'equalto', 'eth0') | first }}"
# Outside IP used for connecting to the supernode from the Internet
service_ipv4_address: >-
  {{ wan_interface.ip_addresses |
      map(attribute='address') |
      ansible.utils.ipv4 |
      ansible.utils.ipaddr('public') |
      first
  }}

loopback_interface: "{{ interfaces | selectattr('name', 'equalto', 'lo') | first }}"
service_ipv6_address: "{{ gateway_ipv6_address }}"

domain_ipv6_subnet: "{{ gateway_ipv6_address | ansible.utils.ipaddr('network/prefix') }}"

batbone_interface: "{{ interfaces | selectattr('name', 'equalto', 'eth1') | first }}"
