routers:
  - name: CR3
    bgp_peer_ipv4_address: "45.151.166.3"
    bgp_peer_ipv6_address: "2001:678:b7c::3"
  - name: CR4
    bgp_peer_ipv4_address: "45.151.166.4"
    bgp_peer_ipv6_address: "2001:678:b7c::4"

fastd_secret: "c08f6ce77b2ec0d4a8f4f448c2b0c13ce7973fc7039d0fce11f89fe50433f844"
fastd_peer_public: "8a486f7b27324cd41761636e40b3bb6e9c1b183588cc997af93c593fb15d4667"

client_ipv4_container: "10.0.0.0/8"
client_bridge_interface: "{{ interfaces | selectattr('name', 'equalto', 'br0') | first }}"
gateway_ipv4_address: >
  {{ client_bridge_interface.ip_addresses |
      map(attribute='address') |
      ansible.utils.ipv4 |
      ansible.utils.ipaddr(client_ipv4_container)
  }}
