- name: Create client bridge
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/network/{{ item }}
  loop:
    - client-bridge.netdev
    - client-bridge.network
  notify: reload network
