- name: Create client bridge
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/network/{{ item }}
  loop:
    - client-bridge.netdev
    - client-bridge.network
  notify: reload network

- name: Enable routing
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "2"
    sysctl_set: true

- name: Install DNS forwarder
  ansible.builtin.package:
    name: dnsmasq
    state: present

- name: Configure DNS forwarder
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: restart dnsmasq

- name: Install firewall helper
  ansible.builtin.package:
    name: iptables-persistent
    state: present

- name: Configure IPv4 firewall rules
  ansible.builtin.template:
    src: firewall.v4.j2
    dest: /etc/iptables/rules.v4
  notify: restart netfilter-persistent

- name: Configure IPv6 firewall rules
  ansible.builtin.template:
    src: firewall.v6.j2
    dest: /etc/iptables/rules.v6
  notify: restart netfilter-persistent

- name: Enable firewall helper
  ansible.builtin.service:
    name: netfilter-persistent
    state: started
    enabled: true
