- name: Create client bridge
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/network/{{ item }}
  loop:
    - client-bridge.netdev
    - client-bridge.network
  notify: reload network

- name: Enable routing
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "2"
    sysctl_set: true

- name: Install DNS forwarder
  ansible.builtin.package:
    name: dnsmasq
    state: present

- name: Configure DNS forwarder
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: restart dnsmasq
