---
- hosts: all
  become: true
  roles:
    - { role: kernel-full, tags: kernel-full }
    - { role: service-ip, tags: service-ip }
    - { role: fastd, tags: fastd }
    - { role: batman, tags: batman }
