---
- name: Refresh package sources
  apt:
    update_cache: true

- name: Ensure full kernel
  package:
    name: linux-image-amd64
    state: present
  notify: reboot

- name: Remove cloud kernel
  package:
    name:
      - linux-image-cloud-amd64
      - linux-image-*-cloud-amd64
    state: absent
  notify: reboot

- name: Flush handlers
  meta: flush_handlers
