---
# This is a hack to generate a fastd-compatible secret key
# from a 32-byte (64-char hex) seed (`fastd_secret_seed` var).
#
# It's needed since there is no way to generate a stable
# fastd secret key directly without the fastd binary. We, however,
# want to store the key in our config management so it stays stable.
#
# The fact that `fastd --generate-key` only reads 32 bytes
# from /dev/random is an implementation detail
# but unlikely to change unless the key generation
# changes entirely.

- ansible.builtin.tempfile:
    state: file
    prefix: fastd_seed_
  changed_when: false
  register: seed_file
- ansible.builtin.copy:
    content: "{{ fastd_secret_seed }}"
    dest: "{{ seed_file.path }}"
  changed_when: false
- ansible.builtin.command:
    argv:
      - systemd-nspawn
      - --directory=/
      - --volatile
      - --bind={{ seed_file.path }}:/dev/random
      - --
      - fastd
      - --generate-key
      - --machine-readable
  register: fastd_secret_gen
  changed_when: false
- ansible.builtin.file:
    path: "{{ seed_file.path }}"
    state: absent
  changed_when: false
