- name: reload network
  ansible.builtin.service:
    name: systemd-networkd
    state: reloaded

- name: restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: reload nftables
  ansible.builtin.service:
    name: nftables
    state: reloaded
