---
- name: Install packages
  ansible.builtin.package:
    name: batctl
    state: present

- name: Load kernel modules
  community.general.modprobe:
    name: batman-adv
    state: present

- name: Make kernel modules persistent
  ansible.builtin.lineinfile:
    dest: /etc/modules-load.d/batman.conf
    line: batman-adv
    create: true

- name: Configure Networking
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/network/{{ item }}"
  loop:
    - batman.netdev
    - batman.network
    - batman-bridge.netdev
    - batman-bridge.network
    - batbone.link
    - batbone.network
  notify: reload network
